<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFs7bRCR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFs7bRCR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFs7bRCR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFs7bRCR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFs7bRCR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fs7bRCR',
    'container.build_id' => 'f0c1e428',
    'container.build_time' => 1779630628,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFs7bRCR');
